// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eAkademik.API;

namespace eAkademik.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220404190142_CreateUserTable")]
    partial class CreateUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("eAkademik.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bebdce4-307b-4b33-8be5-7aa48ad99296"),
                            Email = "jankowalski@gmail.com",
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Password = "test"
                        },
                        new
                        {
                            Id = new Guid("46e57479-fd7e-4a88-98d6-1e4955d120b9"),
                            Email = "adamnowak@gmail.com",
                            FirstName = "Adam",
                            LastName = "Nowak",
                            Password = "test"
                        },
                        new
                        {
                            Id = new Guid("3cc29f11-4b32-4b36-8d2f-8c1d65da046e"),
                            Email = "ewakiwak@gmail.com",
                            FirstName = "Ewa",
                            LastName = "Kiwak",
                            Password = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
