// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eAkademik.API;

#nullable disable

namespace eAkademik.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220515161136_UpdateUserSeedPassword")]
    partial class UpdateUserSeedPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eAkademik.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bebdce4-307b-4b33-8be5-7aa48ad99296"),
                            Email = "jankowalski@gmail.com",
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            Password = "$2a$09$e0UfR4G9hzFYbvpPHLx3ruEJQ8PcMTg6kCXXn3ll1G2x6Qa90J5Lm"
                        },
                        new
                        {
                            Id = new Guid("46e57479-fd7e-4a88-98d6-1e4955d120b9"),
                            Email = "adamnowak@gmail.com",
                            FirstName = "Adam",
                            IsDeleted = false,
                            LastName = "Nowak",
                            Password = "$2a$09$e0UfR4G9hzFYbvpPHLx3ruEJQ8PcMTg6kCXXn3ll1G2x6Qa90J5Lm"
                        },
                        new
                        {
                            Id = new Guid("3cc29f11-4b32-4b36-8d2f-8c1d65da046e"),
                            Email = "ewakiwak@gmail.com",
                            FirstName = "Ewa",
                            IsDeleted = false,
                            LastName = "Kiwak",
                            Password = "$2a$09$e0UfR4G9hzFYbvpPHLx3ruEJQ8PcMTg6kCXXn3ll1G2x6Qa90J5Lm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
